name: Build

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'LLVM Version'
        required: true
        default: '18.1.8'

env:
  BUILD_TYPE: Release
  IS_GITHUB_WORKFLOW: On

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Configure to use MinGW-w64
        shell: bash
        run: |
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
      - name: Download LLVM Source Code
        run: curl -o llvm-source-tree.tar.xz -L https://github.com/llvm/llvm-project/releases/download/llvmorg-${{github.event.inputs.llvm_version}}/llvm-project-${{github.event.inputs.llvm_version}}.src.tar.xz
      - name: Extract LLVM Source Code
        run: |
          7z x llvm-source-tree.tar.xz
          tar xf llvm-source-tree.tar
          mv llvm-project-${{github.event.inputs.llvm_version}}.src llvm
      - name: Build LLVM from Source
        working-directory: ${{github.workspace}}/llvm/llvm
        shell: bash
        run: |
          x86_64-w64-mingw32-gcc -v
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_STANDARD_LIBRARIES="-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -lcomctl32 -lpsapi -Wl,-Bdynamic" -G Ninja
          cmake --build build
      - name: Archive Build Result
        uses: a7ul/tar-action@v1.1.3
        working-directory: ${{github.workspace}}/llvm/llvm
        with:
          command: c
          files: build
          outPath: prebuilt-llvm-${{github.event.inputs.llvm_version}}-x86_64-pc-windows-gnu.tar.gz
      - name: Release
        uses: IsaacShelton/update-existing-release@v1.3.4
        working-directory: ${{github.workspace}}/llvm/llvm
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release: llvm-${{github.event.inputs.llvm_version}}
          body: Prebuilt binaries for LLVM ${{github.event.inputs.llvm_version}}
          replace: true
          files: >
            prebuilt-llvm-${{github.event.inputs.llvm_version}}-x86_64-pc-windows-gnu.tar.gz

